import fs from 'fs'
import path from 'path'

const langs = [
  'fr', 'nl', 'de', 'it', 'es', 'pt', 'el', 'da', 'fi', 'sv', 'hr', 'et',
  'hu', 'lv', 'lt', 'mt', 'pl', 'sk', 'sl', 'cs', 'bg', 'ga', 'ro', 'en'
]

function T(fr, nl, de, it, es, pt, el, da, fi, sv, hr, et, hu, lv, lt, mt, pl, sk, sl, cs, bg, ga, ro, en) {
  return { fr, nl, de, it, es, pt, el, da, fi, sv, hr, et, hu, lv, lt, mt, pl, sk, sl, cs, bg, ga, ro, en }
}

const missingKeys = {
  // ── Common additions ─────────────────────────────────────────────────────
  "common.unknown": T("Inconnu", "Onbekend", "Unbekannt", "Sconosciuto", "Desconocido", "Desconhecido", "Άγνωστο", "Ukendt", "Tuntematon", "Okänt", "Nepoznato", "Teadmata", "Ismeretlen", "Nezināms", "Nežinoma", "Mhux magħruf", "Nieznany", "Neznámy", "Neznano", "Neznámý", "Неизвестно", "Anaithnid", "Necunoscut", "Unknown"),

  // ── Time additions ───────────────────────────────────────────────────────
  "time.today": T("Aujourd'hui", "Vandaag", "Heute", "Oggi", "Hoy", "Hoje", "Σήμερα", "I dag", "Tänään", "Idag", "Danas", "Täna", "Ma", "Šodien", "Šiandien", "Illum", "Dzisiaj", "Dnes", "Danes", "Dnes", "Днес", "Inniu", "Azi", "Today"),
  "time.yesterday": T("Hier", "Gisteren", "Gestern", "Ieri", "Ayer", "Ontem", "Χθες", "I går", "Eilen", "Igår", "Jučer", "Eile", "Tegnap", "Vakar", "Vakar", "Il-bieraħ", "Wczoraj", "Včera", "Včeraj", "Včera", "Вчера", "Inné", "Ieri", "Yesterday"),
  "time.daysAgo": T("Il y a {{count}} jours", "{{count}} dagen geleden", "Vor {{count}} Tagen", "{{count}} giorni fa", "Hace {{count}} días", "Há {{count}} dias", "Πριν από {{count}} ημέρες", "{{count}} dage siden", "{{count}} päivää sitten", "För {{count}} dagar sedan", "Prije {{count}} dana", "{{count}} päeva tagasi", "{{count}} napja", "Pirms {{count}} dienām", "Prieš {{count}} dienas", "{{count}} jiem ilu", "{{count}} dni temu", "Pred {{count}} dňami", "Pred {{count}} dnevi", "Před {{count}} dny", "Преди {{count}} дни", "{{count}} lá ó shin", "Acum {{count}} zile", "{{count}} days ago"),
  "time.hoursAgo": T("Il y a {{count}} heures", "{{count}} uur geleden", "Vor {{count}} Stunden", "{{count}} ore fa", "Hace {{count}} horas", "Há {{count}} horas", "Πριν από {{count}} ώρες", "{{count}} timer siden", "{{count}} tuntia sitten", "För {{count}} timmar sedan", "Prije {{count}} sata", "{{count}} tundi tagasi", "{{count}} órája", "Pirms {{count}} stundām", "Prieš {{count}} valandas", "{{count}} sigħat ilu", "{{count}} godzin temu", "Pred {{count}} hodinami", "Pred {{count}} urami", "Před {{count}} hodinami", "Преди {{count}} часа", "{{count}} uair an chloig ó shin", "Acum {{count}} ore", "{{count}} hours ago"),
  "time.minutesAgo": T("Il y a {{count}} minutes", "{{count}} minuten geleden", "Vor {{count}} Minuten", "{{count}} minuti fa", "Hace {{count}} minutos", "Há {{count}} minutos", "Πριν από {{count}} λεπτά", "{{count}} minutter siden", "{{count}} minuuttia sitten", "För {{count}} minuter sedan", "Prije {{count}} minute", "{{count}} minutit tagasi", "{{count}} perce", "Pirms {{count}} minūtēm", "Prieš {{count}} minutes", "{{count}} minuti ilu", "{{count}} minut temu", "Pred {{count}} minútami", "Pred {{count}} minutami", "Před {{count}} minutami", "Преди {{count}} минути", "{{count}} nóiméad ó shin", "Acum {{count}} minute", "{{count}} minutes ago"),
  "time.justNow": T("À l'instant", "Zojuist", "Gerade eben", "Proprio ora", "Ahora mismo", "Agora mesmo", "Μόλις τώρα", "Lige nu", "Juuri nyt", "Alldeles nyss", "Upravo sada", "Just nüüd", "Épp most", "Tikko", "Ką tik", "Ħaddan", "Przed chwilą", "Práve teraz", "Pravkar", "Právě teď", "Току-що", "Anois díreach", "Chiar acum", "Just now"),
  "time.remainingDaysHours": T("{{days}}j {{hours}}h restantes", "Nog {{days}}d {{hours}}u", "Noch {{days}}T {{hours}}Std", "{{days}}g {{hours}}h rimanenti", "{{days}}d {{hours}}h restantes", "Faltam {{days}}d {{hours}}h", "{{days}}η {{hours}}ω απομένουν", "{{days}}d {{hours}}t tilbage", "{{days}} pv {{hours}} h jäljellä", "{{days}}d {{hours}}h kvar", "Preostalo {{days}}d {{hours}}s", "{{days}}p {{hours}}t jäänud", "Hátralévő {{days}}n {{hours}}ó", "Atlicis {{days}}d {{hours}}h", "Liko {{days}}d. {{hours}}val.", "{{days}}j {{hours}}s li jiftejmu", "Pozostało {{days}}d {{hours}}g", "Zostáva {{days}}d {{hours}}h", "Preostaja {{days}}d {{hours}}ur", "Zbývá {{days}}d {{hours}}h", "Остават {{days}}д {{hours}}ч", "{{days}}l {{hours}}u fágtha", "Mai sunt {{days}}z {{hours}}h", "{{days}}d {{hours}}h remaining"),
  "time.remainingHours": T("{{hours}}h restante", "Nog {{hours}} uur", "Noch {{hours}} Stunden", "{{hours}}h rimanente", "{{hours}}h restante", "Faltam {{hours}}h", "{{hours}}ω απομένει", "{{hours}} timer tilbage", "{{hours}} h jäljellä", "{{hours}}h kvar", "Preostalo {{hours}}s", "{{hours}}t jäänud", "Hátralévő {{hours}}ó", "Atlicis {{hours}}h", "Liko {{hours}}val.", "{{hours}}s li jiftejmu", "Pozostało {{hours}}g", "Zostáva {{hours}}h", "Preostaja {{hours}}ur", "Zbývá {{hours}}h", "Остават {{hours}}ч", "{{hours}}u fágtha", "Mai sunt {{hours}}h", "{{hours}}h remaining"),

  // ── Groups additions ─────────────────────────────────────────────────────
  "groups.broadcastModeAllCanPost": T("Tous les membres peuvent publier", "Alle leden kunnen plaatsen", "Alle Mitglieder können posten", "Tutti i membri possono pubblicare", "Todos los miembros pueden publicar", "Todos os membros podem publicar", "Όλα τα μέλη μπορούν να δημοσιεύσουν", "Alle medlemmer kan skrive", "Kaikki jäsenet voivat julkaista", "Alla medlemmar kan publicera", "Svi članovi mogu objavljivati", "Kõik liikmed saavad postitada", "Minden tag közzétehet", "Visi dalībnieki var publicēt", "Visi nariai gali skelbti", "Il-membri kollha jistgħu jippubblikaw", "Wszyscy członkowie mogą publikować", "Všetci členovia môžu publikovať", "Vsi člani lahko objavljajo", "Všichni členové mohou publikovat", "Всички членове могат да публикуват", "Is féidir le gach ball a fhoilsiú", "Toți membrii pot publica", "All members can post"),
  "groups.broadcastModeDisabled": T("Mode diffusion désactivé", "Uitzendmodus uitgeschakeld", "Broadcast-Modus deaktiviert", "Modalità broadcast disattivata", "Modo difusión desactivado", "Modo de transmissão desativado", "Η λειτουργία εκπομπής απενεργοποιήθηκε", "Broadcast-tilstand deaktiveret", "Lähetystila poistettu käytöstä", "Sändningsläge avstängt", "Način emitiranja isključen", "Edastusrežiim välja lülitatud", "Közvetítési mód kikapcsolva", "Pārraides režīms izslēgts", "Transliacijos režimas išjungtas", "Modalità tax-xandir mitfiija", "Tryb broadcast wyłączony", "Režim vysielania vypnutý", "Način oddajanja onemogočen", "Režim vysílání vypnutý", "Режимът на излъчване е изключен", "Mód craolta díchumasaithe", "Mod broadcast dezactivat", "Broadcast mode disabled"),
  "groups.broadcastModeDisabledMessage": T("Tous les membres peuvent maintenant publier des messages.", "Alle leden kunnen nu berichten plaatsen.", "Alle Mitglieder können jetzt Nachrichten veröffentlichen.", "Tutti i membri possono ora pubblicare messaggi.", "Todos los miembros ahora pueden publicar mensajes.", "Todos os membros podem agora publicar mensagens.", "Όλα τα μέλη μπορούν πλέον να δημοσιεύσουν μηνύματα.", "Alle medlemmer kan nu skrive beskeder.", "Kaikki jäsenet voivat nyt julkaista viestejä.", "Alla medlemmar kan nu publicera meddelanden.", "Svi članovi sada mogu objavljivati poruke.", "Kõik liikmed saavad nüüd sõnumeid postitada.", "Most már minden tag közzétehet üzeneteket.", "Visi dalībnieki tagad var publicēt ziņojumus.", "Dabar visi nariai gali skelbti pranešimus.", "Il-membri kollha jistgħu jippubblikaw messaġġi issa.", "Wszyscy członkowie mogą teraz publikować wiadomości.", "Všetci členovia môžu teraz publikovať správy.", "Vsi člani lahko zdaj objavljajo sporočila.", "Všichni členové nyní mohou publikovat zprávy.", "Всички членове вече могат да публикуват съобщения.", "Is féidir le gach ball teachtaireachtaí a fhoilsiú anois.", "Toți membrii pot acum publica mesaje.", "All members can now post messages."),
  "groups.broadcastModeEnabled": T("Mode diffusion activé", "Uitzendmodus ingeschakeld", "Broadcast-Modus aktiviert", "Modalità broadcast attivata", "Modo difusión activado", "Modo de transmissão ativado", "Η λειτουργία εκπομπής ενεργοποιήθηκε", "Broadcast-tilstand aktiveret", "Lähetystila käytössä", "Sändningsläge påslaget", "Način emitiranja uključen", "Edastusrežiim sisse lülitatud", "Közvetítési mód bekapcsolva", "Pārraides režīms ieslēgts", "Transliacijos režimas įjungtas", "Modalità tax-xandir mixgħula", "Tryb broadcast włączony", "Režim vysielania zapnutý", "Način oddajanja omogočen", "Režim vysílání zapnutý", "Режимът на излъчване е включен", "Mód craolta cumasaithe", "Mod broadcast activat", "Broadcast mode enabled"),
  "groups.broadcastModeEnabledMessage": T("Seuls les administrateurs peuvent désormais publier des messages.", "Alleen beheerders kunnen nu berichten plaatsen.", "Nur Administratoren können jetzt Nachrichten veröffentlichen.", "Solo gli amministratori possono ora pubblicare messaggi.", "Solo los administradores ahora pueden publicar mensajes.", "Apenas os administradores podem agora publicar mensagens.", "Μόνο οι διαχειριστές μπορούν πλέον να δημοσιεύσουν μηνύματα.", "Kun administratorer kan nu skrive beskeder.", "Vain ylläpitäjät voivat nyt julkaista viestejä.", "Endast administratörer kan nu publicera meddelanden.", "Samo administratori sada mogu objavljivati poruke.", "Ainult administraatorid saavad nüüd sõnumeid postitada.", "Most már csak az adminisztrátorok tehetnek közzé üzeneteket.", "Tagad tikai administratori var publicēt ziņojumus.", "Dabar tik administratoriai gali skelbti pranešimus.", "Bissol l-amministraturi jistgħu jippubblikaw messaġġi issa.", "Tylko administratorzy mogą teraz publikować wiadomości.", "Iba administrátori môžu teraz publikovať správy.", "Samo skrbniki lahko zdaj objavljajo sporočila.", "Nyní mohou publikovat zprávy pouze správci.", "Само администраторите вече могат да публикуват съобщения.", "Ní féidir ach riarthóirí teachtaireachtaí a fhoilsiú anois.", "Doar administratorii pot acum publica mesaje.", "Only admins can now post messages."),
  "groups.copyInviteKey": T("Copier la clé d'invitation", "Uitnodigingssleutel kopiëren", "Einladungsschlüssel kopieren", "Copia chiave di invito", "Copiar clave de invitación", "Copiar chave de convite", "Αντιγραφή κλειδιού πρόσκλησης", "Kopiér invitationsnøgle", "Kopioi kutsuavain", "Kopiera inbjudningsnyckel", "Kopiraj pozivni ključ", "Kopeeri kutsevõti", "Meghívó kulcs másolása", "Kopēt ielūguma atslēgu", "Kopijuoti kvietimo raktą", "Kopja ċ-ċavetta tal-invitazzjoni", "Kopiuj klucz zaproszenia", "Kopírovať pozvánkový kľúč", "Kopiraj povabilni ključ", "Kopírovat pozvánkový klíč", "Копиране на поканителния ключ", "Cóipeáil eochair cuiridh", "Copiază cheia invitație", "Copy invite key"),
  "groups.createGroupFailed": T("Échec de la création du groupe", "Groep maken mislukt", "Gruppenerstellung fehlgeschlagen", "Creazione gruppo fallita", "Error al crear el grupo", "Falha ao criar grupo", "Αποτυχία δημιουργίας ομάδας", "Oprettelse af gruppe mislykkedes", "Ryhmän luominen epäonnistui", "Det gick inte att skapa gruppen", "Stvaranje grupe nije uspjelo", "Grupi loomine ebaõnnestus", "A csoport létrehozása sikertelen", "Grupas izveide neizdevās", "Grupės kūrimas nepavyko", "Mur il-grupp ma rnexxiex", "Tworzenie grupy nie powiodło się", "Vytvorenie skupiny zlyhalo", "Ustvarjanje skupine ni uspelo", "Vytvoření skupiny selhalo", "Създаването на групата неуспешно", "Theip ar chruthú an ghrúpa", "Crearea grupului a eșuat", "Failed to create group"),
  "groups.createdAt": T("Créé le", "Aangemaakt op", "Erstellt am", "Creato il", "Creado el", "Criado em", "Δημιουργήθηκε στις", "Oprettet den", "Luotu", "Skapad den", "Stvoreno", "Loodud", "Létrehozva", "Izveidots", "Sukurta", "Maħluq", "Utworzono", "Vytvorené", "Ustvarjeno", "Vytvořeno", "Създадено на", "Cruthaithe", "Creat la", "Created"),
  "groups.descriptionOptional": T("Description (facultative)", "Beschrijving (optioneel)", "Beschreibung (optional)", "Descrizione (facoltativa)", "Descripción (opcional)", "Descrição (opcional)", "Περιγραφή (προαιρετικά)", "Beskrivelse (valgfri)", "Kuvaus (valinnainen)", "Beskrivning (valfri)", "Opis (neobavezan)", "Kirjeldus (valikuline)", "Leírás (opcionális)", "Apraksts (neobligāts)", "Aprašymas (neprivalomas)", "Deskrizzjoni (fakoltattiva)", "Opis (opcjonalny)", "Popis (nepovinný)", "Opis (neobvezen)", "Popis (nepovinný)", "Описание (незадължително)", "Cur síos (roghnach)", "Descriere (opțională)", "Description (optional)"),
  "groups.enterGroupName": T("Saisissez un nom de groupe", "Voer een groepsnaam in", "Geben Sie einen Gruppennamen ein", "Inserisci un nome di gruppo", "Introduce un nombre de grupo", "Introduza um nome de grupo", "Εισαγάγετε όνομα ομάδας", "Indtast et gruppenavn", "Anna ryhmän nimi", "Ange ett gruppnamn", "Unesite naziv grupe", "Sisestage rühma nimi", "Adjon meg egy csoportnevet", "Ievadiet grupas nosaukumu", "Įveskite grupės pavadinimą", "Daħħal isem tal-grupp", "Wprowadź nazwę grupy", "Zadajte názov skupiny", "Vnesite ime skupine", "Zadejte název skupiny", "Въведете име на група", "Cuir isteach ainm an ghrúpa", "Introdu un nume de grup", "Enter group name"),
  "groups.general": T("Général", "Algemeen", "Allgemein", "Generale", "General", "Geral", "Γενικά", "Generelt", "Yleinen", "Allmänt", "Općenito", "Üldine", "Általános", "Vispārīgi", "Bendras", "Ġenerali", "Ogólny", "Všeobecné", "Splošno", "Obecné", "Общ", "Ginearálta", "General", "General"),
  "groups.groupCreated": T("Groupe créé", "Groep aangemaakt", "Gruppe erstellt", "Gruppo creato", "Grupo creado", "Grupo criado", "Η ομάδα δημιουργήθηκε", "Gruppe oprettet", "Ryhmä luotu", "Grupp skapad", "Grupa stvorena", "Grupp loodud", "Csoport létrehozva", "Grupa izveidota", "Grupė sukurta", "Grupp maħluq", "Grupa utworzona", "Skupina vytvorená", "Skupina ustvarjena", "Skupina vytvořena", "Групата е създадена", "Grúpa cruthaithe", "Grup creat", "Group created"),
  "groups.inviteKeyGenerated": T("Clé d'invitation générée", "Uitnodigingssleutel gegenereerd", "Einladungsschlüssel generiert", "Chiave di invito generata", "Clave de invitación generada", "Chave de convite gerada", "Το κλειδί πρόσκλησης δημιουργήθηκε", "Invitationsnøgle genereret", "Kutsuavain luotu", "Inbjudningsnyckel genererad", "Pozivni ključ generiran", "Kutsevõti genereeritud", "Meghívó kulcs generálva", "Ielūguma atslēga ģenerēta", "Kvietimo raktas sukurtas", "Ċavetta tal-invitazzjoni ġġenerata", "Klucz zaproszenia wygenerowany", "Pozvánkový kľúč vygenerovaný", "Povabilni ključ generiran", "Pozvánkový klíč vygenerován", "Поканителният ключ е генериран", "Eochair cuiridh ginte", "Cheie invitație generată", "Invite key generated"),
  "groups.leaveGroupFailed": T("Échec lors de la sortie du groupe", "Groep verlaten mislukt", "Gruppe verlassen fehlgeschlagen", "Uscita dal gruppo fallita", "Error al salir del grupo", "Falha ao sair do grupo", "Αποτυχία εξόδου από ομάδα", "Forladelse af gruppe mislykkedes", "Ryhmästä poistuminen epäonnistui", "Det gick inte att lämna gruppen", "Napuštanje grupe nije uspjelo", "Grupist lahkumine ebaõnnestus", "A csoport elhagyása sikertelen", "Grupas atstāšana neizdevās", "Išėjimas iš grupės nepavyko", "Mur ħarġet mill-grupp ma rnexxiex", "Opuszczenie grupy nie powiodło się", "Opustenie skupiny zlyhalo", "Zapustitev skupine ni uspelo", "Opuštění skupiny selhalo", "Напускането на групата неуспешно", "Theip ar an ngrúpa a fhágáil", "Părăsirea grupului a eșuat", "Failed to leave group"),
  "groups.memberCount": T("{{count}} membre", "{{count}} lid", "{{count}} Mitglied", "{{count}} membro", "{{count}} miembro", "{{count}} membro", "{{count}} μέλος", "{{count}} medlem", "{{count}} jäsen", "{{count}} medlem", "{{count}} član", "{{count}} liige", "{{count}} tag", "{{count}} biedrs", "{{count}} narys", "{{count}} membru", "{{count}} członek", "{{count}} člen", "{{count}} član", "{{count}} člen", "{{count}} член", "{{count}} comhalta", "{{count}} membru", "{{count}} member"),
  "groups.memberRemoveFailed": T("Échec de l'exclusion du membre", "Lid verwijderen mislukt", "Mitglied entfernen fehlgeschlagen", "Rimozione membro fallita", "Error al expulsar miembro", "Falha ao remover membro", "Αποτυχία αφαίρεσης μέλους", "Fjernelse af medlem mislykkedes", "Jäsenen poistaminen epäonnistui", "Det gick inte att ta bort medlemmen", "Uklanjanje člana nije uspjelo", "Liikme eemaldamine ebaõnnestus", "Tag eltávolítása sikertelen", "Dalībnieka noņemšana neizdevās", "Nario pašalinimas nepavyko", "Neħħis il-membru ma rnexxiex", "Usunięcie członka nie powiodło się", "Odstránenie člena zlyhalo", "Odstranitev člana ni uspelo", "Odstranění člena selhalo", "Премахването на член неуспешно", "Theip ar bhall a bhaint", "Îndepărtarea membrului a eșuat", "Failed to remove member"),
  "groups.memberRemoved": T("Membre exclu", "Lid verwijderd", "Mitglied entfernt", "Membro rimosso", "Miembro expulsado", "Membro removido", "Το μέλος αφαιρέθηκε", "Medlem fjernet", "Jäsen poistettu", "Medlem borttagen", "Član uklonjen", "Liige eemaldatud", "Tag eltávolítva", "Dalībnieks noņemts", "Narys pašalintas", "Membru tneħħa", "Członek usunięty", "Člen odstránený", "Član odstranjen", "Člen odstraněn", "Членът е премахнат", "Ball bainte", "Membru îndepărtat", "Member removed"),
  "groups.messageChannel": T("Canal de messages", "Berichtenkanaal", "Nachrichtenkanal", "Canale messaggi", "Canal de mensajes", "Canal de mensagens", "Κανάλι μηνυμάτων", "Beskedkanal", "Viestikanava", "Meddelandekanal", "Kanal poruka", "Sõnumikanal", "Üzenetcsatorna", "Ziņu kanāls", "Žinučių kanalas", "Kanal tal-messaġġi", "Kanał wiadomości", "Kanál správ", "Sporočilni kanal", "Kanál zpráv", "Канал за съобщения", "Cainéal teachtaireachta", "Canal mesaje", "Message channel"),
  "groups.onlineMembers": T("{{count}} en ligne", "{{count}} online", "{{count}} online", "{{count}} in linea", "{{count}} en línea", "{{count}} online", "{{count}} σε σύνδεση", "{{count}} online", "{{count}} paikalla", "{{count}} online", "{{count}} na mreži", "{{count}} võrgus", "{{count}} elérhető", "{{count}} tiešsaistē", "{{count}} prisijungę", "{{count}} online", "{{count}} online", "{{count}} online", "{{count}} na spletu", "{{count}} online", "{{count}} на линия", "{{count}} ar líne", "{{count}} online", "{{count}} online"),
  "groups.ownerLeaveMessage": T("Vous êtes propriétaire de ce groupe. Transférez la propriété ou supprimez le groupe pour partir.", "U bent eigenaar van deze groep. Draag het eigendom over of verwijder de groep om te vertrekken.", "Sie sind Besitzer dieser Gruppe. Übertragen Sie den Besitz oder löschen Sie die Gruppe, um zu gehen.", "Sei il proprietario di questo gruppo. Trasferisci la proprietà o elimina il gruppo per andartene.", "Eres propietario de este grupo. Transfiere la propiedad o elimina el grupo para salir.", "És proprietário deste grupo. Transfere a propriedade ou elimina o grupo para sair.", "Είστε ιδιοκτήτης αυτής της ομάδας. Μεταβιβάστε την ιδιοκτησία ή διαγράψτε την ομάδα για να φύγετε.", "Du er ejer af denne gruppe. Overfør ejerskab eller slet gruppen for at forlade den.", "Olet tämän ryhmän omistaja. Siirrä omistajuus tai poista ryhmä poistuaksesi.", "Du är ägare av denna grupp. Överför ägandet eller ta bort gruppen för att lämna.", "Vi ste vlasnik ove grupe. Prenesite vlasništvo ili izbrišite grupu da biste otišli.", "Olete selle grupi omanik. Omandi ülekandmiseks või grupi lahkumiseks kustutage grupp.", "Ön ennek a csoportnak a tulajdonosa. A távozáshoz adja át a tulajdonjogot, vagy törölje a csoportot.", "Jūs esat šīs grupas īpašnieks. Lūdzu, nododiet īpašumtiesības vai dzēsiet grupu, lai aizietu.", "Jūs esate šios grupės savininkas. Perduokite nuosavybę arba ištrinkite grupę, kad išeitumėte.", "Int sid tal-grupp. Ittrasferixxi s-sid jew ħassar il-grupp biex tħalli.", "Jesteś właścicielem tej grupy. Aby odejść, przenieś własność lub usuń grupę.", "Ste vlastníkom tejto skupiny. Na odchod preneste vlastníctvo alebo odstráňte skupinu.", "Lastnik ste te skupine. Za odhod prenesite lastništvo ali izbrišite skupino.", "Jste vlastníkem této skupiny. Chcete-li odejít, převeďte vlastnictví nebo skupinu smažte.", "Вие сте собственик на тази група. Прехвърлете собствеността или изтрийте групата, за да напуснете.", "Is tú úinéir an ghrúpa seo. Aistrigh an t-úinéireacht nó scrios an grúpa chun imeacht.", "Ești proprietarul acestui grup. Transferă proprietatea sau șterge grupul pentru a pleca.", "You own this group. Transfer ownership or delete the group to leave."),
  "groups.roleUpdateFailed": T("Échec de la mise à jour du rôle", "Rol bijwerken mislukt", "Rollenaktualisierung fehlgeschlagen", "Aggiornamento ruolo fallito", "Error al actualizar rol", "Falha ao atualizar cargo", "Αποτυχία ενημέρωσης ρόλου", "Rolleopdatering mislykkedes", "Roolin päivitys epäonnistui", "Det gick inte att uppdatera rollen", "Ažuriranje uloge nije uspjelo", "Rolli värskendamine ebaõnnestus", "Szerepkör frissítése sikertelen", "Lomas atjaunināšana neizdevās", "Vaidmens atnaujinimas nepavyko", "Aġġornament tar-rwol ma rnexxiex", "Aktualizacja roli nie powiodła się", "Aktualizácia roly zlyhala", "Posodobitev vloge ni uspela", "Aktualizace role selhala", "Обновяването на ролята неуспешно", "Theip ar an ról a nuashonrú", "Actualizarea rolului a eșuat", "Failed to update role"),
  "groups.roleUpdated": T("Rôle mis à jour", "Rol bijgewerkt", "Rolle aktualisiert", "Ruolo aggiornato", "Rol actualizado", "Cargo atualizado", "Ο ρόλος ενημερώθηκε", "Rolle opdateret", "Rooli päivitetty", "Roll uppdaterad", "Uloga ažurirana", "Roll värskendatud", "Szerepkör frissítve", "Loma atjaunināta", "Vaidmuo atnaujintas", "Rwol aġġornat", "Rola zaktualizowana", "Rola aktualizovaná", "Vloga posodobljena", "Role aktualizována", "Ролята е актуализирана", "Ról nuashonraithe", "Rol actualizat", "Role updated"),
  "groups.startAudioGroupCall": T("Appel audio de groupe", "Groepsaudio-oproep", "Gruppen-Audioanruf", "Chiamata audio di gruppo", "Llamada de audio grupal", "Chamada de áudio em grupo", "Ομαδική κλήση ήχου", "Gruppe lydopkald", "Ryhmääänipuhelu", "Gruppsamtal ljud", "Grupni audio poziv", "Grupi helikõne", "Csoportos hanghívás", "Grupas audiozvans", "Grupinis garso skambutis", "Sejħa awdjo tal-grupp", "Grupowe połączenie audio", "Skupinový audiohovor", "Skupinski avdio klic", "Skupinový audio hovor", "Групов аудио разговор", "Glóigrúpa fuaime", "Apel audio de grup", "Start audio group call"),
  "groups.startVideoGroupCall": T("Appel vidéo de groupe", "Groepsvideo-oproep", "Gruppen-Videoanruf", "Videochiamata di gruppo", "Videollamada grupal", "Chamada de vídeo em grupo", "Ομαδική βιντεοκλήση", "Gruppe videoopkald", "Ryhmävideopuhelu", "Gruppsamtal video", "Grupni video poziv", "Grupi videokõne", "Csoportos videóhívás", "Grupas videozvans", "Grupinis vaizdo skambutis", "Sejħa video tal-grupp", "Grupowe połączenie wideo", "Skupinový videohovor", "Skupinski video klic", "Skupinový videohovor", "Групов видео разговор", "Glóigrúpa físeáin", "Apel video de grup", "Start video group call"),
  "groups.toggleMembers": T("Afficher/masquer les membres", "Leden tonen/verbergen", "Mitglieder ein-/ausblenden", "Mostra/nascondi membri", "Mostrar/ocultar miembros", "Mostrar/ocultar membros", "Εμφάνιση/απόκρυψη μελών", "Vis/skjul medlemmer", "Näytä/piilota jäsenet", "Visa/dölj medlemmar", "Prikaži/sakrij članove", "Näita/peida liikmeid", "Tagok megjelenítése/elrejtése", "Rādīt/paslēpt dalībniekus", "Rodyti/slėpti narius", "Uri/ħabi l-membri", "Pokaż/ukryj członków", "Zobraziť/skryť členov", "Prikaži/skrij člane", "Zobrazit/skrýt členy", "Показване/скриване на членовете", "Taispeáin/folaigh baill", "Afișează/ascunde membrii", "Toggle members"),

  // ── Panels additions ─────────────────────────────────────────────────────
  "panels.encryptionDescription": T("Vos messages sont chiffrés de bout en bout. Seuls les participants de cette conversation peuvent les lire.", "Je berichten zijn end-to-end versleuteld. Alleen deelnemers aan dit gesprek kunnen ze lezen.", "Ihre Nachrichten sind Ende-zu-Ende-verschlüsselt. Nur die Teilnehmer dieses Gesprächs können sie lesen.", "I tuoi messaggi sono crittografati end-to-end. Solo i partecipanti a questa conversazione possono leggerli.", "Tus mensajes están cifrados de extremo a extremo. Solo los participantes de esta conversación pueden leerlos.", "As tuas mensagens estão encriptadas de ponta a ponta. Apenas os participantes desta conversação as podem ler.", "Τα μηνύματά σας είναι κρυπτογραφημένα από άκρο σε άκρο. Μόνο οι συμμετέχοντες σε αυτήν τη συνομιλία μπορούν να τα διαβάσουν.", "Dine beskeder er end-to-end-krypteret. Kun deltagere i denne samtale kan læse dem.", "Viestisi on päästä päähän salattu. Vain tämän keskustelun osallistujat voivat lukea ne.", "Dina meddelanden är end-to-end-krypterade. Endast deltagare i denna konversation kan läsa dem.", "Vaše poruke su šifrirane od kraja do kraja. Samo sudionici ovog razgovora mogu ih pročitati.", "Teie sõnumid on otspõhiliselt krüpteeritud. Selle vestluse osalejad saavad neid lugeda.", "Az üzenetei végpontok között vannak titkosítva. Csak ennek a beszélgetésnek a résztvevői olvashatják el.", "Jūsu ziņas ir šifrētas gala-punktā. Tikai šīs sarunas dalībnieki tās var lasīt.", "Jūsų žinutės užšifruotos iš galo į galą. Tik šio pokalbio dalyviai gali jas perskaityti.", "Il-messaġġi tiegħek huma cifrati end-to-end. Biss il-parteċipanti ta' din il-konversazzjoni jistgħu jaqrawhom.", "Twoje wiadomości są szyfrowane end-to-end. Tylko uczestnicy tej rozmowy mogą je przeczytać.", "Vaše správy sú šifrované end-to-end. Títo konverzácie môžu čítať len jej účastníci.", "Vaša sporočila so šifrirana od konca do konca. Samo udeleženci tega pogovora jih lahko preberejo.", "Vaše zprávy jsou šifrovány end-to-end. Tuto konverzaci mohou číst pouze její účastníci.", "Вашите съобщения са криптирани от край до край. Само участниците в този разговор могат да ги прочетат.", "Tá do theachtaireachtaí criptithe ceann-go-ceann. Ní féidir ach rannpháirtithe sa chomhrá seo iad a léamh.", "Mesajele tale sunt criptate end-to-end. Doar participanții la această conversație le pot citi.", "Your messages are end-to-end encrypted. Only participants in this conversation can read them."),

  // ── Settings additions ───────────────────────────────────────────────────
  "settings.accentColor": T("Couleur d'accentuation", "Accentkleur", "Akzentfarbe", "Colore accento", "Color de acento", "Cor de destaque", "Χρώμα έμφασης", "Accentfarve", "Korostusväri", "Accentfärg", "Boja naglaska", "Aktsendivärv", "Kiemelőszín", "Akcenta krāsa", "Paryškintos spalvos", "Kulur tal-akkċent", "Kolor akcentu", "Farba akcentu", "Barva poudarka", "Barva zvýraznění", "Акцентен цвят", "Dath aiciúint", "Culoare accent", "Accent color"),
  "settings.activeLinks": T("Liens actifs", "Actieve links", "Aktive Links", "Link attivi", "Enlaces activos", "Links ativos", "Ενεργοί σύνδεσμοι", "Aktive links", "Aktiiviset linkit", "Aktiva länkar", "Aktivne poveznice", "Aktiivsed lingid", "Aktív linkek", "Aktīvās saites", "Aktyvios nuorodos", "Links attivi", "Aktywne linki", "Aktívne odkazy", "Aktivne povezave", "Aktivní odkazy", "Активни връзки", "Naisc ghníomhacha", "Linkuri active", "Active links"),
  "settings.added": T("Ajouté", "Toegevoegd", "Hinzugefügt", "Aggiunto", "Añadido", "Adicionado", "Προστέθηκε", "Tilføjet", "Lisätty", "Tillagd", "Dodano", "Lisatud", "Hozzáadva", "Pievienots", "Pridėta", "Miżjud", "Dodano", "Pridané", "Dodano", "Přidáno", "Добавен", "Curtha leis", "Adăugat", "Added"),
  "settings.all": T("Tout", "Alle", "Alle", "Tutti", "Todos", "Todos", "Όλα", "Alle", "Kaikki", "Alla", "Sve", "Kõik", "Mind", "Visi", "Visi", "Kollha", "Wszystkie", "Všetky", "Vsi", "Vše", "Всички", "Gach", "Toate", "All"),
  "settings.audio": T("Audio", "Audio", "Audio", "Audio", "Audio", "Áudio", "Ήχος", "Lyd", "Audio", "Ljud", "Audio", "Audio", "Audio", "Audio", "Garso", "Awdjo", "Audio", "Audio", "Avdio", "Audio", "Аудио", "Fuaime", "Audio", "Audio"),
  "settings.backgroundColor": T("Couleur d'arrière-plan", "Achtergrondkleur", "Hintergrundfarbe", "Colore sfondo", "Color de fondo", "Cor de fundo", "Χρώμα φόντου", "Baggrundsfarve", "Taustaväri", "Bakgrundsfärg", "Boja pozadine", "Taustavärv", "Háttérszín", "Fona krāsa", "Fono spalva", "Kulur tal-isfond", "Kolor tła", "Farba pozadia", "Barva ozadja", "Barva pozadí", "Фонов цвят", "Dath cúlra", "Culoare fundal", "Background color"),
  "settings.borderColor": T("Couleur de bordure", "Randkleur", "Rahmenfarbe", "Colore bordo", "Color de borde", "Cor da borda", "Χρώμα περιγράμματος", "Kantfarve", "Reunaväri", "Kantfärg", "Boja ruba", "Äärisvärv", "Szegélyszín", "Malas krāsa", "Rėmelio spalva", "Kulur tal-konfini", "Kolor obramowania", "Farba okraja", "Barva obrobe", "Barva ohraničení", "Цвят на рамката", "Dath na teorann", "Culoare contur", "Border color"),
  "settings.borderRadius": T("Arrondi des coins", "Hoekradius", "Eckenradius", "Raggio bordo", "Radio de esquina", "Raio do canto", "Ακτίνα γωνίας", "Hjørneradius", "Kulmasäde", "Hörnradie", "Radijus ruba", "Nurga raadius", "Sarokkerekítés", "Stūru rādiuss", "Kampų spindulys", "Raġġu tal-kantunieri", "Promień zaokrąglenia", "Polomer okraja", "Polmer robov", "Poloměr zaoblení", "Радиус на ъгълите", "Ga na himper", "Raza colțurilor", "Border radius"),
  "settings.clearAll": T("Tout effacer", "Alles wissen", "Alle löschen", "Cancella tutto", "Borrar todo", "Limpar tudo", "Εκκαθάριση όλων", "Ryd alle", "Tyhjennä kaikki", "Rensa alla", "Očisti sve", "Kustuta kõik", "Mindent töröl", "Notīrīt visu", "Išvalyti viską", "Ħassar kollox", "Wyczyść wszystko", "Vymazať všetko", "Počisti vse", "Vymazat vše", "Изчисти всички", "Glan gach rud", "Șterge tot", "Clear all"),
  "settings.clearFavoritesConfirm": T("Vider les favoris ?", "Favorieten wissen?", "Favoriten löschen?", "Cancellare i preferiti?", "¿Vaciar favoritos?", "Limpar favoritos?", "Εκκαθάριση αγαπημένων;", "Ryd favoritter?", "Tyhjennä suosikit?", "Rensa favoriter?", "Očisti favorite?", "Kustuta lemmikud?", "Kedvencek törlése?", "Notīrīt izlases?", "Išvalyti mėgstamus?", "Ħassar il-favoriti?", "Wyczyścić ulubione?", "Vymazať obľúbené?", "Počisti priljubljene?", "Vymazat oblíbené?", "Изчисти любимите?", "Glan na ceanáin?", "Golește favorite?", "Clear favorites?"),
  "settings.colorEditor": T("Éditeur de couleurs", "Kleurenbewerker", "Farb-Editor", "Editor colori", "Editor de colores", "Editor de cores", "Επεξεργαστής χρωμάτων", "Farveeditor", "Värieditori", "Färgredigerare", "Uređivač boja", "Värviredaktor", "Színszerkesztő", "Krāsu redaktors", "Spalvų redaktorius", "Editur tal-kuluri", "Edytor kolorów", "Editor farieb", "Urejevalnik barv", "Editor barev", "Редактор на цветове", "Eagarthóir dathanna", "Editor culori", "Color editor"),
  "settings.complete": T("Terminé", "Voltooid", "Abgeschlossen", "Completato", "Completado", "Concluído", "Ολοκληρώθηκε", "Afsluttet", "Valmis", "Klart", "Dovršeno", "Lõpetatud", "Kész", "Pabeigts", "Baigta", "Tlestaq", "Zakończono", "Dokončené", "Dokončano", "Dokončeno", "Завършено", "Críochnaithe", "Finalizat", "Complete"),
  "settings.copyLink": T("Copier le lien", "Link kopiëren", "Link kopieren", "Copia link", "Copiar enlace", "Copiar link", "Αντιγραφή συνδέσμου", "Kopiér link", "Kopioi linkki", "Kopiera länk", "Kopiraj poveznicu", "Kopeeri link", "Link másolása", "Kopēt saiti", "Kopijuoti nuorodą", "Kopja l-link", "Kopiuj link", "Kopírovať odkaz", "Kopiraj povezavo", "Kopírovat odkaz", "Копиране на връзката", "Cóipeáil an nasc", "Copiază linkul", "Copy link"),
  "settings.created": T("Créé", "Aangemaakt", "Erstellt", "Creato", "Creado", "Criado", "Δημιουργήθηκε", "Oprettet", "Luotu", "Skapad", "Stvoreno", "Loodud", "Létrehozva", "Izveidots", "Sukurta", "Maħluq", "Utworzono", "Vytvorené", "Ustvarjeno", "Vytvořeno", "Създадено", "Cruthaithe", "Creat", "Created"),
  "settings.customColors": T("Couleurs personnalisées", "Aangepaste kleuren", "Benutzerdefinierte Farben", "Colori personalizzati", "Colores personalizados", "Cores personalizadas", "Προσαρμοσμένα χρώματα", "Tilpassede farver", "Mukautetut värit", "Anpassade färger", "Prilagođene boje", "Kohandatud värvid", "Egyéni színek", "Pielāgotās krāsas", "Tinkintos spalvos", "Kuluri personalizzati", "Kolory niestandardowe", "Vlastné farby", "Barve po meri", "Vlastní barvy", "Персонализирани цветове", "Dathanna saincheaptha", "Culori personalizate", "Custom colors"),
  "settings.customColorsDescription": T("Personnalisez les couleurs de l'interface pour correspondre à votre style.", "Pas de interfacekleuren aan aan uw stijl.", "Passen Sie die Farben der Benutzeroberfläche an Ihren Stil an.", "Personalizza i colori dell'interfaccia in base al tuo stile.", "Personaliza los colores de la interfaz para que coincidan con tu estilo.", "Personalize as cores da interface para corresponder ao seu estilo.", "Προσαρμόστε τα χρώματα της διεπαφής στο στυλ σας.", "Tilpas grænsefladens farver til din stil.", "Mukauta käyttöliittymän värit omaan tyyliisi.", "Anpassa gränssnittets färger efter din stil.", "Prilagodite boje sučelja svom stilu.", "Kohanda liidese värve oma stiiliga.", "Szabja személyre a felület színeit a stílusához.", "Pielāgojiet saskarnes krāsas savam stilam.", "Derinkite sąsajos spalvas pagal savo stilių.", "Personalizza l-kuluri tal-interfaċċa skond il-stil tiegħek.", "Dostosuj kolory interfejsu do swojego stylu.", "Prispôsobte farby rozhrania svojmu štýlu.", "Prilagodite barve vmesnika svojemu slogu.", "Přizpůsobte barvy rozhraní svému stylu.", "Персонализирайте цветовете на интерфейса според вашия стил.", "Saincheap dathanna an chomhéadain d'fhonn do stíle.", "Personalizați culorile interfeței pentru a se potrivi stilului dvs.", "Customize interface colors to match your style."),
  "settings.deletePermanently": T("Supprimer définitivement", "Definitief verwijderen", "Dauerhaft löschen", "Elimina definitivamente", "Eliminar permanentemente", "Eliminar permanentemente", "Μόνιμη διαγραφή", "Slet permanent", "Poista pysyvästi", "Ta bort permanent", "Trajno izbriši", "Kustuta jäädavalt", "Végleges törlés", "Dzēst uz visiem laikiem", "Ištrinti visam laikui", "Ħassar b'mod permanenti", "Usuń trwale", "Odstrániť natrvalo", "Trajno izbriši", "Trvale odstranit", "Изтрий за постоянно", "Scrios go buan", "Șterge permanent", "Delete permanently"),
  "settings.deletedFilesWillAppearHere": T("Les fichiers supprimés apparaîtront ici.", "Verwijderde bestanden verschijnen hier.", "Gelöschte Dateien erscheinen hier.", "I file eliminati appariranno qui.", "Los archivos eliminados aparecerán aquí.", "Os ficheiros eliminados aparecerão aqui.", "Τα διαγραμμένα αρχεία θα εμφανιστούν εδώ.", "Slettede filer vises her.", "Poistetut tiedostot ilmestyvät tänne.", "Raderade filer visas här.", "Izbrisane datoteke pojavit će se ovdje.", "Kustutatud failid ilmuvad siia.", "A törölt fájlok itt jelennek meg.", "Dzēstās datnes parādīsies šeit.", "Ištrinti failai atsiras čia.", "Il-fajls miċħuda jidher hawn.", "Usunięte pliki pojawią się tutaj.", "Vymazané súbory sa tu zobrazia.", "Izbrisane datoteke se bodo prikazale tukaj.", "Odstraněné soubory se zobrazí zde.", "Изтритите файлове ще се появят тук.", "Beidh comhaid scriosta le feiceáil anseo.", "Fișierele șterse vor apărea aici.", "Deleted files will appear here."),
  "settings.deselectAll": T("Tout désélectionner", "Alles deselecteren", "Alle abwählen", "Deseleziona tutto", "Deseleccionar todo", "Desselecionar tudo", "Αποεπιλογή όλων", "Fravælg alle", "Poista valinnat", "Avmarkera alla", "Poništi sve odabire", "Tühista kõik valikud", "Kijelölés törlése", "Noņemt visu atlasi", "Panaikinti visus žymėjimus", "Neħti l-għażliet kollha", "Odznacz wszystkie", "Zrušiť všetky výbery", "Prekliči vse izbire", "Zrušit všechny výběry", "Премахни всички избори", "Díroghnaigh gach rud", "Deselectează tot", "Deselect all"),
  "settings.documents": T("Documents", "Documenten", "Dokumente", "Documenti", "Documentos", "Documentos", "Έγγραφα", "Dokumenter", "Asiakirjat", "Dokument", "Dokumenti", "Dokumendid", "Dokumentumok", "Dokumenti", "Dokumentai", "Dokumenti", "Dokumenty", "Dokumenty", "Dokumenti", "Dokumenty", "Документи", "Cáipéisí", "Documente", "Documents"),
  "settings.downloading": T("Téléchargement", "Downloaden", "Herunterladen", "Download in corso", "Descargando", "A transferir", "Λήψη", "Downloader", "Ladataan", "Laddar ner", "Preuzimanje", "Allalaadimine", "Letöltés", "Lejupielāde", "Atsisiunčiama", "Niżżel", "Pobieranie", "Sťahovanie", "Prenašanje", "Stahování", "Изтегляне", "Ag íoslódáil", "Se descarcă", "Downloading"),
  "settings.downloadsWillAppearHere": T("Les téléchargements apparaîtront ici.", "Downloads verschijnen hier.", "Downloads erscheinen hier.", "I download appariranno qui.", "Las descargas aparecerán aquí.", "As transferências aparecerão aqui.", "Οι λήψεις θα εμφανιστούν εδώ.", "Downloads vises her.", "Lataukset ilmestyvät tänne.", "Nedladdningar visas här.", "Preuzimanja će se pojaviti ovdje.", "Allalaadimised ilmuvad siia.", "A letöltések itt jelennek meg.", "Lejupielādes parādīsies šeit.", "Atsisiuntimai atsiras čia.", "Id-downloads jidru hawn.", "Pobrania pojawią się tutaj.", "Stiahnutia sa tu zobrazia.", "Prenosi se bodo prikazali tukaj.", "Stahování se zobrazí zde.", "Изтегленията ще се появят тук.", "Beidh íosluchtuithe le feiceáil anseo.", "Descărcările vor apărea aici.", "Downloads will appear here."),
  "settings.emptyTrashConfirm": T("Vider la corbeille ?", "Prullenbak legen?", "Papierkorb leeren?", "Svuotare il cestino?", "¿Vaciar papelera?", "Esvaziar lixo?", "Αδειασμός κάδου;", "Tøm papirkurv?", "Tyhjennä roskakori?", "Töm papperskorgen?", "Isprazni smeće?", "Tühjenda prügikast?", "Kuka ürítése?", "Iztukšot miskasti?", "Išvalyti šiukšlinę?", "Ħassar il-basket?", "Opróżnić kosz?", "Vysypať kôš?", "Izprazni koš?", "Vysypat koš?", "Изпразни кошчето?", "Glan an bruscar?", "Golește coșul?", "Empty trash?"),
  "settings.emptyTrashWarning": T("Cette action supprimera définitivement tous les éléments de la corbeille.", "Deze actie verwijdert alle items permanent uit de prullenbak.", "Diese Aktion löscht alle Elemente dauerhaft aus dem Papierkorb.", "Questa azione eliminerà definitivamente tutti gli elementi dal cestino.", "Esta acción eliminará permanentemente todos los elementos de la papelera.", "Esta ação irá eliminar permanentemente todos os itens do lixo.", "Αυτή η ενέργεια θα διαγράψει μόνιμα όλα τα αντικείμενα από τον κάδο.", "Denne handling sletter alle elementer permanent fra papirkurven.", "Tämä toiminto poistaa kaikki roskakorin kohteet pysyvästi.", "Denna åtgärd tar permanent bort alla objekt från papperskorgen.", "Ova radnja će trajno izbrisati sve stavke iz smeća.", "See toiming kustutab prügikastist kõik esemed jäädavalt.", "Ez a művelet véglegesen törli a kuka összes elemét.", "Šī darbība neatgriezeniski izdzēsīs visus vienumus no miskastes.", "Šis veiksmas visam laikui ištrins visus šiukšlių dėžės elementus.", "Din il-azzjoni tneħħi b'mod permanenti l-oġġetti kollha mill-basket.", "Ta czynność trwale usunie wszystkie elementy z kosza.", "Táto akcia natrvalo odstráni všetky položky z koša.", "To dejanje bo trajno izbrisalo vse predmete iz koša.", "Tato akce trvale odstraní všechny položky z koše.", "Това действие ще изтрие за постоянно всички елементи от кошчето.", "Scrifidh an gníomh seo gach mír go buan ón mbruscar.", "Această acțiune va șterge definitiv toate elementele din coș.", "This action will permanently delete all items from trash."),
  "settings.expired": T("Expiré", "Verlopen", "Abgelaufen", "Scaduto", "Expirado", "Expirado", "Έληξε", "Udløbet", "Vanhentunut", "Utgången", "Isteklo", "Aegunud", "Lejárt", "Beidzies", "Pasibaigęs", "Skada", "Wygasło", "Platnosť vypršala", "Poteklo", "Platnost vypršela", "Изтекъл", "As dáta", "Expirat", "Expired"),
  "settings.failedTransfers": T("{{count}} transfert échoué", "{{count}} mislukte overdracht", "{{count}} fehlgeschlagene Übertragung", "{{count}} trasferimento fallito", "{{count}} transferencia fallida", "{{count}} transferência falhada", "{{count}} αποτυχημένη μεταφορά", "{{count}} mislykket overførsel", "{{count}} epäonnistunut siirto", "{{count}} misslyckad överföring", "{{count}} neuspjeli prijenos", "{{count}} ebaõnnestunud ülekanne", "{{count}} sikertelen átvitel", "{{count}} neizdevusies pārsūtīšana", "{{count}} nepavykęs perkėlimas", "{{count}} trasferiment fallut", "{{count}} nieudany transfer", "{{count}} neúspešný prenos", "{{count}} neuspešen prenos", "{{count}} neúspěšný přenos", "{{count}} неуспешен трансфер", "{{count}} aistriuchán teipthe", "{{count}} transfer eșuat", "{{count}} failed transfer"),
  "settings.failedTransfers_plural": T("{{count}} transferts échoués", "{{count}} mislukte overdrachten", "{{count}} fehlgeschlagene Übertragungen", "{{count}} trasferimenti falliti", "{{count}} transferencias fallidas", "{{count}} transferências falhadas", "{{count}} αποτυχημένες μεταφορές", "{{count}} mislykkede overførsler", "{{count}} epäonnistunutta siirtoa", "{{count}} misslyckade överföringar", "{{count}} neuspjela prijenosa", "{{count}} ebaõnnestunud ülekannet", "{{count}} sikertelen átvitel", "{{count}} neizdevušās pārsūtīšanas", "{{count}} nepavykusių perkėlimų", "{{count}} trasferimenti falluti", "{{count}} nieudanych transferów", "{{count}} neúspešných prenosov", "{{count}} neuspešnih prenosov", "{{count}} neúspěšných přenosů", "{{count}} неуспешни трансфера", "{{count}} aistriúcháin teipthe", "{{count}} transferuri eșuate", "{{count}} failed transfers"),
  "settings.favoriteFiles": T("Fichiers favoris", "Favoriete bestanden", "Favorisierte Dateien", "File preferiti", "Archivos favoritos", "Ficheiros favoritos", "Αγαπημένα αρχεία", "Favoritfiler", "Suosikk tiedostot", "Favoritfiler", "Omiljene datoteke", "Lemmikfailid", "Kedvenc fájlok", "Izlases datnes", "Mėgstami failai", "Fajls favoriti", "Ulubione pliki", "Obľúbené súbory", "Priljubljene datoteke", "Oblíbené soubory", "Любими файлове", "Comhaid is fearr", "Fișiere favorite", "Favorite files"),
  "settings.fileType_all": T("Tous les types", "Alle typen", "Alle Typen", "Tutti i tipi", "Todos los tipos", "Todos os tipos", "Όλοι οι τύποι", "Alle typer", "Kaikki tyypit", "Alla typer", "Sve vrste", "Kõik tüübid", "Minden típus", "Visi tipi", "Visi tipai", "It-tipijiet kollha", "Wszystkie typy", "Všetky typy", "Vsi tipi", "Všechny typy", "Всички видове", "Gach cineál", "Toate tipurile", "All types"),
  "settings.fileType_application": T("Documents", "Documenten", "Dokumente", "Documenti", "Documentos", "Documentos", "Έγγραφα", "Dokumenter", "Asiakirjat", "Dokument", "Dokumenti", "Dokumendid", "Dokumentumok", "Dokumenti", "Dokumentai", "Dokumenti", "Dokumenty", "Dokumenty", "Dokumenti", "Dokumenty", "Документи", "Cáipéisí", "Documente", "Documents"),
  "settings.fileType_audio": T("Audio", "Audio", "Audio", "Audio", "Audio", "Áudio", "Ήχος", "Lyd", "Audio", "Ljud", "Audio", "Audio", "Audio", "Audio", "Garso", "Awdjo", "Audio", "Audio", "Avdio", "Audio", "Аудио", "Fuaime", "Audio", "Audio"),
  "settings.fileType_image": T("Images", "Afbeeldingen", "Bilder", "Immagini", "Imágenes", "Imagens", "Εικόνες", "Billeder", "Kuvat", "Bilder", "Slike", "Pildid", "Képek", "Attēli", "Vaizdai", "Stampi", "Obrazy", "Obrázky", "Slike", "Obrázky", "Изображения", "Íomhánna", "Imagini", "Images"),
  "settings.fileType_video": T("Vidéos", "Video's", "Videos", "Video", "Vídeos", "Vídeos", "Βίντεο", "Videoer", "Videot", "Videor", "Videozapisi", "Videod", "Videók", "Video", "Vaizdo įrašai", "Vidjos", "Filmy", "Videá", "Videoposnetki", "Videa", "Видеоклипове", "Físeáin", "Videoclipuri", "Videos"),
  "settings.files": T("Fichiers", "Bestanden", "Dateien", "File", "Archivos", "Ficheiros", "Αρχεία", "Filer", "Tiedostot", "Filer", "Datoteke", "Failid", "Fájlok", "Datnes", "Failai", "Fajls", "Pliki", "Súbory", "Datoteke", "Soubory", "Файлове", "Comhaid", "Fișiere", "Files"),
  "settings.filter": T("Filtre", "Filter", "Filter", "Filtro", "Filtro", "Filtro", "Φίλτρο", "Filter", "Suodatin", "Filter", "Filter", "Filter", "Szűrő", "Filtrs", "Filtras", "Filtru", "Filtr", "Filter", "Filter", "Filtr", "Филтър", "Scagaire", "Filtru", "Filter"),
  "settings.images": T("Images", "Afbeeldingen", "Bilder", "Immagini", "Imágenes", "Imagens", "Εικόνες", "Billeder", "Kuvat", "Bilder", "Slike", "Pildid", "Képek", "Attēli", "Vaizdai", "Stampi", "Obrazy", "Obrázky", "Slike", "Obrázky", "Изображения", "Íomhánna", "Imagini", "Images"),
  "settings.noFavoriteFiles": T("Aucun fichier favori", "Geen favoriete bestanden", "Keine favorisierten Dateien", "Nessun file preferito", "Sin archivos favoritos", "Sem ficheiros favoritos", "Κανένα αγαπημένο αρχείο", "Ingen favoritfiler", "Ei suosikkitiedostoja", "Inga favoritfiler", "Nema omiljenih datoteka", "Lemmikfaile pole", "Nincsenek kedvenc fájlok", "Nav izlašu datņu", "Nėra mėgstamų failų", "Ebda fajls favoriti", "Brak ulubionych plików", "Žiadne obľúbené súbory", "Ni priljubljenih datotek", "Žádné oblíbené soubory", "Няма любими файлове", "Níl aon chomhad is fearr", "Niciun fișier favorit", "No favorite files"),
  "settings.noFavoritesMatch": T("Aucun favori ne correspond", "Geen favorieten gevonden", "Keine Favoriten gefunden", "Nessun preferito corrisponde", "Ningún favorito coincide", "Nenhum favorito corresponde", "Κανένα αγαπημένο δεν ταιριάζει", "Ingen favoritter matcher", "Ei vastaavia suosikkeja", "Inga favoriter matchar", "Nema odgovarajućih omiljenih", "Ükski lemmik ei sobi", "Nincs egyező kedvenc", "Nav atbilstošu izlašu", "Nėra atitinkančių mėgstamų", "Ebda favoriti jaqblu", "Brak pasujących ulubionych", "Žiadne vyhovujúce obľúbené", "Ni ustreznih priljubljenih", "Žádné odpovídající oblíbené", "Няма съвпадащи любими", "Gan aon cheanáin a mheaitseáil", "Niciun favorit nu se potrivește", "No favorites match"),
  "settings.removeFromFavorites": T("Retirer des favoris", "Verwijderen uit favorieten", "Aus Favoriten entfernen", "Rimuovi dai preferiti", "Quitar de favoritos", "Remover dos favoritos", "Αφαίρεση από αγαπημένα", "Fjern fra favoritter", "Poista suosikeista", "Ta bort från favoriter", "Ukloni iz omiljenih", "Eemalda lemmikutest", "Eltávolítás a kedvencekből", "Noņemt no izlases", "Pašalinti iš mėgstamų", "Neħħi mill-favoriti", "Usuń z ulubionych", "Odstrániť z obľúbených", "Odstrani iz priljubljenih", "Odebrat z oblíbených", "Премахни от любими", "Bain ó na ceanáin", "Elimină din favorite", "Remove from favorites"),
  "settings.removeSelected": T("Supprimer la sélection", "Geselecteerde verwijderen", "Ausgewählte entfernen", "Rimuovi selezionati", "Eliminar seleccionados", "Remover selecionados", "Αφαίρεση επιλεγμένων", "Fjern valgte", "Poista valitut", "Ta bort markerade", "Ukloni odabrano", "Eemalda valitud", "Kijelöltek eltávolítása", "Noņemt atlasītos", "Pašalinti pasirinktus", "Neħħi l-għażla", "Usuń wybrane", "Odstrániť vybraté", "Odstrani izbrane", "Odstranit vybrané", "Премахни избраните", "Bain na cinn roghnaithe", "Elimină selecția", "Remove selected"),
  "settings.revoke": T("Révoquer", "Intrekken", "Widerrufen", "Revoca", "Revocar", "Revogar", "Ανάκληση", "Tilbagekald", "Peruuta", "Återkalla", "Opozovi", "Tühista", "Visszavonás", "Atsaukt", "Atšaukti", "Revoka", "Cofnij", "Zrušiť", "Prekliči", "Odvolat", "Отмени", "Cúlghairm", "Revocă", "Revoke"),
  "settings.revokeAll": T("Tout révoquer", "Alles intrekken", "Alle widerrufen", "Revoca tutto", "Revocar todo", "Revogar tudo", "Ανάκληση όλων", "Tilbagekald alle", "Peruuta kaikki", "Återkalla alla", "Opozovi sve", "Tühista kõik", "Mind visszavon", "Atsaukt visu", "Atšaukti visus", "Revoka kollha", "Cofnij wszystko", "Zrušiť všetko", "Prekliči vse", "Odvolat vše", "Отмени всички", "Cúlghairm uile", "Revocă toate", "Revoke all"),
  "settings.searchDownloads": T("Rechercher dans les téléchargements…", "Zoek in downloads…", "Downloads durchsuchen…", "Cerca nei download…", "Buscar en descargas…", "Pesquisar transferências…", "Αναζήτηση στις λήψεις…", "Søg i downloads…", "Hae latauksista…", "Sök i nedladdningar…", "Pretraži preuzimanja…", "Otsi allalaadimistest…", "Keresés a letöltésekben…", "Meklēt lejupielādēs…", "Ieškoti atsisiuntimuose…", "Fittex downloads…", "Szukaj w pobranych…", "Hľadať v stiahnutých…", "Išči v prenosih…", "Hledat ve stahování…", "Търси в изтеглянията…", "Cuardaigh íosluchtuithe…", "Caută în descărcări…", "Search downloads…"),
  "settings.searchFavorites": T("Rechercher dans les favoris…", "Zoek in favorieten…", "Favoriten durchsuchen…", "Cerca nei preferiti…", "Buscar en favoritos…", "Pesquisar favoritos…", "Αναζήτηση στα αγαπημένα…", "Søg i favoritter…", "Hae suosikeista…", "Sök i favoriter…", "Pretraži favorite…", "Otsi lemmikutest…", "Keresés a kedvencekben…", "Meklēt izlasēs…", "Ieškoti mėgstamuose…", "Fittex favoriti…", "Szukaj w ulubionych…", "Hľadať v obľúbených…", "Išči med priljubljenimi…", "Hledat v oblíbených…", "Търси в любимите…", "Cuardaigh ceanáin…", "Caută în favorite…", "Search favorites…"),
  "settings.secondaryColor": T("Couleur secondaire", "Secundaire kleur", "Sekundärfarbe", "Colore secondario", "Color secundario", "Cor secundária", "Δευτερεύον χρώμα", "Sekundær farve", "Toissijainen väri", "Sekundärfärg", "Sekundarna boja", "Sekundaarne värv", "Másodlagos szín", "Sekundārā krāsa", "Antrinė spalva", "Kulur sekondarju", "Kolor dodatkowy", "Sekundárna farba", "Sekundarna barva", "Sekundární barva", "Вторичен цвят", "Dath tánaisteach", "Culoare secundară", "Secondary color"),
  "settings.selectAll": T("Tout sélectionner", "Alles selecteren", "Alle auswählen", "Seleziona tutto", "Seleccionar todo", "Selecionar tudo", "Επιλογή όλων", "Vælg alle", "Valitse kaikki", "Markera alla", "Odaberi sve", "Vali kõik", "Összes kijelölése", "Izvēlēties visu", "Pasirinkti visus", "Agħżel kollox", "Zaznacz wszystko", "Vybrať všetko", "Izberi vse", "Vybrat vše", "Избери всички", "Roghnaigh gach rud", "Selectează tot", "Select all"),
  "settings.selectedCount": T("{{count}} sélectionné", "{{count}} geselecteerd", "{{count}} ausgewählt", "{{count}} selezionato", "{{count}} seleccionado", "{{count}} selecionado", "{{count}} επιλεγμένο", "{{count}} valgt", "{{count}} valittu", "{{count}} markerad", "{{count}} odabrano", "{{count}} valitud", "{{count}} kiválasztva", "{{count}} atlasīts", "{{count}} pasirinktas", "{{count}} magħżul", "{{count}} wybrany", "{{count}} vybraté", "{{count}} izbrano", "{{count}} vybráno", "{{count}} избран", "{{count}} roghnaithe", "{{count}} selectat", "{{count}} selected"),
  "settings.selectedCount_plural": T("{{count}} sélectionnés", "{{count}} geselecteerd", "{{count}} ausgewählt", "{{count}} selezionati", "{{count}} seleccionados", "{{count}} selecionados", "{{count}} επιλεγμένα", "{{count}} valgt", "{{count}} valittua", "{{count}} markerade", "{{count}} odabrano", "{{count}} valitud", "{{count}} kiválasztva", "{{count}} atlasīti", "{{count}} pasirinktų", "{{count}} magħżulin", "{{count}} wybranych", "{{count}} vybratých", "{{count}} izbranih", "{{count}} vybraných", "{{count}} избрани", "{{count}} roghnaithe", "{{count}} selectați", "{{count}} selected"),
  "settings.shareLinksDescription": T("Gérez les liens de partage actifs et contrôlez leur expiration.", "Beheer actieve deellinks en beheer hun vervaldatum.", "Verwalten Sie aktive Freigabelinks und steuern Sie deren Ablauf.", "Gestisci i link di condivisione attivi e controlla la loro scadenza.", "Administra los enlaces de compartir activos y controla su vencimiento.", "Gira links de partilha ativos e controla a sua expiração.", "Διαχειριστείτε ενεργούς συνδέσμους κοινής χρήσης και ελέγξτε τη λήξη τους.", "Administrer aktive delingslinks og styr deres udløb.", "Hallinnoi aktiivisia jakolinkkejä ja niiden vanhenemista.", "Hantera aktiva delningslänkar och kontrollera deras utgång.", "Upravljajte aktivnim poveznicama za dijeljenje i nadzirajte njihovo istjecanje.", "Halda aktiivseid jagamislinke ja nende aegumist.", "Kezelje az aktív megosztási linkeket és szabályozza lejáratukat.", "Pārvaldiet aktīvās kopīgošanas saites un kontrolējiet to derīguma termiņu.", "Valdykite aktyvias bendrinimo nuorodas ir kontroliuokite jų galiojimą.", "Immaniġġja l-links attivi tal-qdusija u kkontrolla l-iskadenza tagħhom.", "Zarządzaj aktywnymi linkami udostępniania i kontroluj ich wygaśnięcie.", "Spravujte aktívne odkazy na zdieľanie a kontrolujte ich platnosť.", "Upravljajte aktivnimi povezavami za deljenje in nadzorujte njihovo potek veljavnosti.", "Spravujte aktivní sdílecí odkazy a řiďte jejich expiraci.", "Управлявайте активните връзки за споделяне и контролирайте тяхното изтичане.", "Bainistigh naisc ghníomhacha comhroinne agus smachtaigh a dtréimhse bailíochta.", "Gestionați linkurile active de partajare și controlați expirarea lor.", "Manage active share links and control their expiration."),
  "settings.shareLinksExpiry": T("Expire dans {{days}} jours", "Verloopt over {{days}} dagen", "Läuft in {{days}} Tagen ab", "Scade tra {{days}} giorni", "Expira en {{days}} días", "Expira em {{days}} dias", "Λήγει σε {{days}} ημέρες", "Udløber om {{days}} dage", "Vanhenee {{days}} päivässä", "Upphör om {{days}} dagar", "Istječe za {{days}} dana", "Aegub {{days}} päeva pärast", "Lejárat: {{days}} nap", "Derīgs vēl {{days}} dienas", "Baigsis po {{days}} dienų", "Jiskarżu f'{{days}} ijiem", "Wygasa za {{days}} dni", "Platnosť vyprší o {{days}} dní", "Poteče čez {{days}} dni", "Platnost vyprší za {{days}} dní", "Изтича след {{days}} дни", "As dáta i {{days}} lá", "Expiră în {{days}} zile", "Expires in {{days}} days"),
  "settings.surfaceColor": T("Couleur de surface", "Oppervlaktekleur", "Oberflächenfarbe", "Colore superficie", "Color de superficie", "Cor da superfície", "Χρώμα επιφάνειας", "Overfladefarve", "Pintaväri", "Ytanfärg", "Boja površine", "Pinnavärv", "Felszínszín", "Virsmas krāsa", "Paviršiaus spalva", "Kulur tal-wiċċ", "Kolor powierzchni", "Farba povrchu", "Barva površine", "Barva povrchu", "Цвят на повърхността", "Dath dromchla", "Culoare suprafață", "Surface color"),
  "settings.textPrimaryColor": T("Couleur du texte principal", "Primaire tekstkleur", "Primäre Textfarbe", "Colore testo principale", "Color de texto principal", "Cor do texto principal", "Χρώμα κύριου κειμένου", "Primær tekstfarve", "Ensisijainen tekstiväri", "Primär textfärg", "Boja primarnog teksta", "Esmane tekstivärv", "Elsődleges szövegszín", "Galvenā teksta krāsa", "Pagrindinė teksto spalva", "Kulur tat-test prinċipali", "Kolor tekstu podstawowego", "Farba primárneho textu", "Barva glavnega besedila", "Barva hlavního textu", "Основен цвят на текста", "Dath téacs bunúsach", "Culoare text principal", "Primary text color"),
  "settings.textSecondaryColor": T("Couleur du texte secondaire", "Secundaire tekstkleur", "Sekundäre Textfarbe", "Colore testo secondario", "Color de texto secundario", "Cor do texto secundário", "Χρώμα δευτερεύοντος κειμένου", "Sekundær tekstfarve", "Toissijainen tekstiväri", "Sekundär textfärg", "Boja sekundarnog teksta", "Sekundaarne tekstivärv", "Másodlagos szövegszín", "Sekundārā teksta krāsa", "Antrinė teksto spalva", "Kulur tat-test sekondarju", "Kolor tekstu dodatkowego", "Farba sekundárneho textu", "Barva sekundarnega besedila", "Barva sekundárního textu", "Вторичен цвят на текста", "Dath téacs tánaisteach", "Culoare text secundar", "Secondary text color"),
  "settings.themePresets": T("Préréglages de thème", "Thema-voorinstellingen", "Themenvoreinstellungen", "Preset tema", "Preajustes de tema", "Predefinições de tema", "Προεπιλογές θέματος", "Temaforkonfigurationer", "Teemaesiasetukset", "Temaförinställningar", "Predlošci tema", "Teemade eelseaded", "Témaelőbeállítások", "Tēmas iestatījumi", "Apipavidalinimo išankstinės nuostatos", "Presets tat-tema", "Presety motywów", "Predvoľby tém", "Prednastavitve tem", "Předvolby motivů", "Предварителни настройки на тема", "Réamhshocruithe téama", "Preseturi temă", "Theme presets"),
  "settings.themePresetsDescription": T("Choisissez un point de départ et affinez les couleurs si nécessaire.", "Kies een uitgangspunt en verfijn de kleuren indien nodig.", "Wählen Sie einen Ausgangspunkt und passen Sie die Farben bei Bedarf an.", "Scegli un punto di partenza e affina i colori se necessario.", "Elige un punto de partida y ajusta los colores si es necesario.", "Escolha um ponto de partida e refine as cores se necessário.", "Επιλέξτε ένα σημείο εκκίνησης και βελτιώστε τα χρώματα αν χρειάζεται.", "Vælg et udgangspunkt, og finjuster farverne efter behov.", "Valitse lähtökohta ja hienosäädä värejä tarvittaessa.", "Välj en utgångspunkt och finjustera färgerna vid behov.", "Odaberite polazište i prilagodite boje prema potrebi.", "Valige lähtepunkt ja peenhäälestage värve vajadusel.", "Válasszon kiindulópontot, és finomítsa a színeket szükség szerint.", "Izvēlieties sākumpunktu un nepieciešamības gadījumā pielāgojiet krāsas.", "Pasirinkite pradžios tašką ir prireikus patikslinkite spalvas.", "Agħżel punt tal-bidu u raffina l-kuluri jekk meħtieġ.", "Wybierz punkt wyjścia i dostosuj kolory w razie potrzeby.", "Vyberte východiskový bod a podľa potreby doladite farby.", "Izberite izhodišče in po potrebi dodelajte barve.", "Vyberte výchozí bod a v případě potřeby upravte barvy.", "Изберете начална точка и при необходимост усъвършенствайте цветовете.", "Roghnaigh pointe tosaigh agus feabhsaigh na dathanna más gá.", "Alegeți un punct de plecare și rafinați culorile dacă este necesar.", "Choose a starting point and refine colors if needed."),
  "settings.total": T("Total", "Totaal", "Gesamt", "Totale", "Total", "Total", "Σύνολο", "I alt", "Yhteensä", "Totalt", "Ukupno", "Kokku", "Összesen", "Kopā", "Iš viso", "Total", "Razem", "Celkom", "Skupaj", "Celkem", "Общо", "Iomlán", "Total", "Total"),
  "settings.totalDownloads": T("{{count}} téléchargement", "{{count}} download", "{{count}} Download", "{{count}} download", "{{count}} descarga", "{{count}} transferência", "{{count}} λήψη", "{{count}} download", "{{count}} lataus", "{{count}} nedladdning", "{{count}} preuzimanje", "{{count}} allalaadimine", "{{count}} letöltés", "{{count}} lejupielāde", "{{count}} atsisiuntimas", "{{count}} download", "{{count}} pobranie", "{{count}} stiahnutie", "{{count}} prenos", "{{count}} stažení", "{{count}} изтегляне", "{{count}} íosluchtú", "{{count}} descărcare", "{{count}} download"),
  "settings.totalDownloads_plural": T("{{count}} téléchargements", "{{count}} downloads", "{{count}} Downloads", "{{count}} download", "{{count}} descargas", "{{count}} transferências", "{{count}} λήψεις", "{{count}} downloads", "{{count}} latausta", "{{count}} nedladdningar", "{{count}} preuzimanja", "{{count}} allalaadimist", "{{count}} letöltés", "{{count}} lejupielādes", "{{count}} atsisiuntimų", "{{count}} downloads", "{{count}} pobrań", "{{count}} stiahnutí", "{{count}} prenosov", "{{count}} stažení", "{{count}} изтегляния", "{{count}} íosluchtuithe", "{{count}} descărcări", "{{count}} downloads"),
  "settings.totalSize": T("Taille totale", "Totale grootte", "Gesamtgröße", "Dimensione totale", "Tamaño total", "Tamanho total", "Συνολικό μέγεθος", "Samlet størrelse", "Koko yhteensä", "Total storlek", "Ukupna veličina", "Kogumaht", "Teljes méret", "Kopējais izmērs", "Bendras dydis", "Daqs totali", "Całkowity rozmiar", "Celková veľkosť", "Skupna velikost", "Celková velikost", "Общ размер", "Méid iomlán", "Dimensiune totală", "Total size"),
  "settings.totalTransfers": T("{{count}} transfert", "{{count}} overdracht", "{{count}} Übertragung", "{{count}} trasferimento", "{{count}} transferencia", "{{count}} transferência", "{{count}} μεταφορά", "{{count}} overførsel", "{{count}} siirto", "{{count}} överföring", "{{count}} prijenos", "{{count}} ülekanne", "{{count}} átvitel", "{{count}} pārsūtīšana", "{{count}} perkėlimas", "{{count}} trasferiment", "{{count}} transfer", "{{count}} prenos", "{{count}} prenos", "{{count}} přenos", "{{count}} трансфер", "{{count}} aistriúchán", "{{count}} transfer", "{{count}} transfer"),
  "settings.totalTransfers_plural": T("{{count}} transferts", "{{count}} overdrachten", "{{count}} Übertragungen", "{{count}} trasferimenti", "{{count}} transferencias", "{{count}} transferências", "{{count}} μεταφορές", "{{count}} overførsler", "{{count}} siirtoa", "{{count}} överföringar", "{{count}} prijenosa", "{{count}} ülekannet", "{{count}} átvitel", "{{count}} pārsūtīšanas", "{{count}} perkėlimų", "{{count}} trasferimenti", "{{count}} transferów", "{{count}} prenosov", "{{count}} prenosov", "{{count}} přenosů", "{{count}} трансфера", "{{count}} aistriúcháin", "{{count}} transferuri", "{{count}} transfers"),
  "settings.transferFailed": T("Échec du transfert", "Overdracht mislukt", "Übertragung fehlgeschlagen", "Trasferimento fallito", "Transferencia fallida", "Transferência falhada", "Η μεταφορά απέτυχε", "Overførsel mislykkedes", "Siirto epäonnistui", "Överföring misslyckades", "Prijenos nije uspio", "Ülekanne ebaõnnestus", "Átvitel sikertelen", "Pārsūtīšana neizdevās", "Perkėlimas nepavyko", "Trasferiment fallut", "Transfer nie powiódł się", "Prenos zlyhal", "Prenos ni uspel", "Přenos selhal", "Преносът неуспешен", "Theip ar an aistriú", "Transfer eșuat", "Transfer failed"),
  "settings.transferStatus_complete": T("Terminé", "Voltooid", "Abgeschlossen", "Completato", "Completado", "Concluído", "Ολοκληρώθηκε", "Afsluttet", "Valmis", "Klart", "Dovršeno", "Lõpetatud", "Kész", "Pabeigts", "Baigta", "Tlestaq", "Zakończono", "Dokončené", "Dokončano", "Dokončeno", "Завършено", "Críochnaithe", "Finalizat", "Complete"),
  "settings.transferStatus_downloading": T("Téléchargement", "Downloaden", "Herunterladen", "Download in corso", "Descargando", "A transferir", "Λήψη", "Downloader", "Ladataan", "Laddar ner", "Preuzimanje", "Allalaadimine", "Letöltés", "Lejupielāde", "Atsisiunčiama", "Niżżel", "Pobieranie", "Sťahovanie", "Prenašanje", "Stahování", "Изтегляне", "Ag íoslódáil", "Se descarcă", "Downloading"),
  "settings.transferStatus_error": T("Erreur", "Fout", "Fehler", "Errore", "Error", "Erro", "Σφάλμα", "Fejl", "Virhe", "Fel", "Greška", "Viga", "Hiba", "Kļūda", "Klaida", "Żball", "Błąd", "Chyba", "Napaka", "Chyba", "Грешка", "Earráid", "Eroare", "Error"),
  "settings.transferStatus_uploading": T("Envoi", "Uploaden", "Hochladen", "Caricamento", "Subiendo", "A enviar", "Μεταφόρτωση", "Uploader", "Lähetetään", "Laddar upp", "Prijenos", "Üleslaadimine", "Feltöltés", "Augšupielāde", "Įkeliama", "Ttella'", "Wysyłanie", "Nahrávanie", "Prenašanje", "Nahrávání", "Качване", "Ag uaslódáil", "Se încarcă", "Uploading"),
  "settings.transfer_all": T("Tous", "Alle", "Alle", "Tutti", "Todos", "Todos", "Όλα", "Alle", "Kaikki", "Alla", "Sve", "Kõik", "Mind", "Visi", "Visi", "Kollha", "Wszystkie", "Všetky", "Vsi", "Vše", "Всички", "Gach", "Toate", "All"),
  "settings.transfer_complete": T("Terminés", "Voltooid", "Abgeschlossen", "Completati", "Completados", "Concluídos", "Ολοκληρωμένα", "Afsluttede", "Valmiit", "Klara", "Dovršeni", "Lõpetatud", "Kész", "Pabeigti", "Baigti", "Tlestaq", "Zakończone", "Dokončené", "Dokončani", "Dokončeno", "Завършени", "Críochnaithe", "Finalizate", "Complete"),
  "settings.transfer_downloading": T("Téléchargements", "Downloads", "Downloads", "Download", "Descargas", "Transferências", "Λήψεις", "Downloads", "Lataukset", "Nedladdningar", "Preuzimanja", "Allalaadimised", "Letöltések", "Lejupielādes", "Atsisiuntimai", "Downloads", "Pobieranie", "Sťahovania", "Prenosi", "Stahování", "Изтегляния", "Íosluchtuithe", "Descărcări", "Downloads"),
  "settings.transfer_error": T("Erreurs", "Fouten", "Fehler", "Errori", "Errores", "Erros", "Σφάλματα", "Fejl", "Virheet", "Fel", "Greške", "Vead", "Hibák", "Kļūdas", "Klaidos", "Żbalji", "Błędy", "Chyby", "Napake", "Chyby", "Грешки", "Earráidí", "Erori", "Errors"),
  "settings.transfer_uploading": T("Envois", "Uploads", "Uploads", "Caricamenti", "Subidas", "Envios", "Μεταφορτώσεις", "Uploads", "Lähetykset", "Uppladdningar", "Prijenosi", "Üleslaadimised", "Feltöltések", "Augšupielādes", "Įkėlimai", "Uploads", "Wysyłanie", "Nahrávania", "Prenosi", "Nahrávání", "Качвания", "Uaslódáil", "Încărcări", "Uploads"),
  "settings.transfersWillAppearHere": T("Les transferts actifs apparaîtront ici.", "Actieve overdrachten verschijnen hier.", "Aktive Übertragungen erscheinen hier.", "I trasferimenti attivi appariranno qui.", "Las transferencias activas aparecerán aquí.", "As transferências ativas aparecerão aqui.", "Οι ενεργές μεταφορές θα εμφανιστούν εδώ.", "Aktive overførsler vises her.", "Aktiiviset siirrot ilmestyvät tänne.", "Aktiva överföringar visas här.", "Aktivni prijenosi pojavit će se ovdje.", "Aktiivsed ülekanded ilmuvad siia.", "Az aktív átvitelek itt jelennek meg.", "Aktīvās pārsūtīšanas parādīsies šeit.", "Aktyvūs perkėlimai atsiras čia.", "It-trasferimenti attivi jidru hawn.", "Aktywne transfery pojawią się tutaj.", "Aktívne prenosy sa tu zobrazia.", "Aktivni prenosi se bodo prikazali tukaj.", "Aktivní přenosy se zobrazí zde.", "Активните трансфери ще се появят тук.", "Beidh aistriúcháin ghníomhacha le feiceáil anseo.", "Transferurile active vor apărea aici.", "Active transfers will appear here."),
  "settings.trashItems": T("Éléments", "Items", "Elemente", "Elementi", "Elementos", "Itens", "Στοιχεία", "Elementer", "Kohteet", "Objekt", "Stavke", "Üksused", "Elemek", "Vienumi", "Elementai", "Oġġetti", "Elementy", "Položky", "Elementi", "Položky", "Елементи", "Míreanna", "Elemente", "Items"),
  "settings.trashItemsCount": T("{{count}} élément", "{{count}} item", "{{count}} Element", "{{count}} elemento", "{{count}} elemento", "{{count}} item", "{{count}} στοιχείο", "{{count}} element", "{{count}} kohde", "{{count}} objekt", "{{count}} stavka", "{{count}} üksus", "{{count}} elem", "{{count}} vienums", "{{count}} elementas", "{{count}} oġġett", "{{count}} element", "{{count}} položka", "{{count}} element", "{{count}} položka", "{{count}} елемент", "{{count}} mír", "{{count}} element", "{{count}} item"),
  "settings.trashItemsCount_plural": T("{{count}} éléments", "{{count}} items", "{{count}} Elemente", "{{count}} elementi", "{{count}} elementos", "{{count}} itens", "{{count}} στοιχεία", "{{count}} elementer", "{{count}} kohdetta", "{{count}} objekt", "{{count}} stavke", "{{count}} üksust", "{{count}} elem", "{{count}} vienumi", "{{count}} elementų", "{{count}} oġġetti", "{{count}} elementów", "{{count}} položiek", "{{count}} elementov", "{{count}} položek", "{{count}} елемента", "{{count}} mír", "{{count}} elemente", "{{count}} items"),
  "settings.uploading": T("Envoi", "Uploaden", "Hochladen", "Caricamento", "Subiendo", "A enviar", "Μεταφόρτωση", "Uploader", "Lähetetään", "Laddar upp", "Prijenos", "Üleslaadimine", "Feltöltés", "Augšupielāde", "Įkeliama", "Ttella'", "Wysyłanie", "Nahrávanie", "Prenašanje", "Nahrávání", "Качване", "Ag uaslódáil", "Se încarcă", "Uploading"),
  "settings.videos": T("Vidéos", "Video's", "Videos", "Video", "Vídeos", "Vídeos", "Βίντεο", "Videoer", "Videot", "Videor", "Videozapisi", "Videod", "Videók", "Video", "Vaizdo įrašai", "Vidjos", "Filmy", "Videá", "Videoposnetki", "Videa", "Видеоклипове", "Físeáin", "Videoclipuri", "Videos"),
  "settings.views": T("Vues", "Weergaven", "Aufrufe", "Visualizzazioni", "Vistas", "Visualizações", "Προβολές", "Visninger", "Katselukerrat", "Visningar", "Pregledi", "Vaatamisi", "Megtekintések", "Skatījumi", "Peržiūros", "Viduti", "Wyświetlenia", "Zobrazenia", "Ogledi", "Zobrazení", "Прегледи", "Amharcanna", "Vizualizări", "Views"),
}

function main() {
  const filePath = path.resolve('src/i18n/translations.ts')
  let content = fs.readFileSync(filePath, 'utf8')

  function buildBlock(lang, keys) {
    const lines = []
    for (const [key, translations] of Object.entries(keys)) {
      const value = translations[lang]
      if (value === undefined) {
        throw new Error(`Missing translation for ${key} in ${lang}`)
      }
      lines.push(`      "${key}": "${value}",`)
    }
    return lines.join('\n') + '\n'
  }

  for (const lang of langs) {
    const langBlockRe = new RegExp(`(  ${lang}: \\{[\\s\\S]*?\\n  \\},)`, 'm')
    const match = content.match(langBlockRe)
    if (!match) {
      console.warn(`Language block ${lang} not found`)
      continue
    }
    const block = match[1]
    const newBlock = block.replace(new RegExp('\\n    \\},\\n  \\},'), `\\n${buildBlock(lang, missingKeys)}    },\\n  },`)
    content = content.replace(block, newBlock)
  }

  fs.writeFileSync(filePath, content)
  console.log(`Injected ${Object.keys(missingKeys).length} keys into ${langs.length} languages`)
}

main()
